### ISSUE TITLE
+ "px"

### ISSUE THREAD

**Issue by wiliame** [twygmbh/angular-auto-height#3]
In ionic the directive doesn't works unless you add the "px" in the .css line. Maybe because ionic doesn't use jquery and works with the lite version of angular.

http://i.imgur.com/jhkM0aP.png

**Comment by m43nu** [comment]
This plugin does not have any dependency on jquery, it should work without it.

I will investigate in the missing pixel problem, but I 'm not using or have ever tested it with ionic.

Could it be a browser issue? In which browser did you test it?

**Comment by m43nu** [comment]
This issue is fixed in the new release.
