### ISSUE TITLE
Couldn't pull from Visual Studio Bower

### ISSUE THREAD

**Issue by brianro** [twygmbh/angular-auto-height#5]
Awesome widget. Had to export code and add directly to my project. Couldn't pull using Visual Studio Bower / Nuget. Was hoping you can publish to that site.

**Comment by m43nu** [comment]
Hi @brianro 

It should work with the usual bower install command: `bower install twygmbh/angular-auto-height`
Or what do you mean with Bower / Nuget? Do you need a package in the Nuget-Repository?

**Comment by brianro** [comment]
Yep -  you’re right – it a nuget package access by the VS Bower system. If you add that it becomes highly accessible to the VS.Next system.
